services:
  # API service
  gewechat:
    image: registry.cn-hangzhou.aliyuncs.com/gewe/gewe:latest
    restart: always
    ports:
      - "2531:2531"
      - "2532:2532"
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./data/gewechat:/root/temp
      - ../dify-on-wechat:/dify-on-wechat
    extra_hosts:
      - "host.docker.internal:host-gateway"